[2024-07-14T16:24:29.467+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T16:24:29.548+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.ingest_xlsx manual__2024-07-14T16:24:25.097023+00:00 [queued]>
[2024-07-14T16:24:29.557+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.ingest_xlsx manual__2024-07-14T16:24:25.097023+00:00 [queued]>
[2024-07-14T16:24:29.557+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T16:24:29.582+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): ingest_xlsx> on 2024-07-14 16:24:25.097023+00:00
[2024-07-14T16:24:29.625+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=204) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-14T16:24:29.631+0000] {standard_task_runner.py:63} INFO - Started process 210 to run task
[2024-07-14T16:24:29.628+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'ingest_xlsx', 'manual__2024-07-14T16:24:25.097023+00:00', '--job-id', '202', '--raw', '--subdir', 'DAGS_FOLDER/demo.py', '--cfg-path', '/tmp/tmp7r6tkfyt']
[2024-07-14T16:24:29.637+0000] {standard_task_runner.py:91} INFO - Job 202: Subtask ingest_xlsx
[2024-07-14T16:24:29.711+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_pipeline.ingest_xlsx manual__2024-07-14T16:24:25.097023+00:00 [running]> on host 37d6808b0cee
[2024-07-14T16:24:29.935+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your_email@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='ingest_xlsx' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T16:24:25.097023+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-14T16:24:25.097023+00:00'
[2024-07-14T16:24:29.937+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T16:24:29.947+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T16:24:29.948+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/compat/_optional.py", line 132, in import_optional_dependency
    module = importlib.import_module(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'openpyxl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/demo.py", line 20, in ingest_xlsx
    df_xlsx = pd.read_excel(xlsx_path, sheet_name="Data")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/excel/_base.py", line 504, in read_excel
    io = ExcelFile(
         ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/excel/_base.py", line 1580, in __init__
    self._reader = self._engines[engine](
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/excel/_openpyxl.py", line 552, in __init__
    import_optional_dependency("openpyxl")
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/compat/_optional.py", line 135, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
[2024-07-14T16:24:30.032+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_pipeline, task_id=ingest_xlsx, run_id=manual__2024-07-14T16:24:25.097023+00:00, execution_date=20240714T162425, start_date=20240714T162429, end_date=20240714T162430
[2024-07-14T16:24:30.054+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 202 for task ingest_xlsx (Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.; 210)
[2024-07-14T16:24:30.099+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-14T16:24:30.179+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-14T16:24:30.198+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
