[2024-07-15T04:49:26.373+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-15T04:49:26.393+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.merge_data manual__2024-07-15T04:42:10.842954+00:00 [queued]>
[2024-07-15T04:49:26.399+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.merge_data manual__2024-07-15T04:42:10.842954+00:00 [queued]>
[2024-07-15T04:49:26.399+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-15T04:49:26.418+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): merge_data> on 2024-07-15 04:42:10.842954+00:00
[2024-07-15T04:49:26.428+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'merge_data', 'manual__2024-07-15T04:42:10.842954+00:00', '--job-id', '231', '--raw', '--subdir', 'DAGS_FOLDER/demo.py', '--cfg-path', '/tmp/tmp7oyymcae']
[2024-07-15T04:49:26.429+0000] {standard_task_runner.py:91} INFO - Job 231: Subtask merge_data
[2024-07-15T04:49:26.431+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=391) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-15T04:49:26.432+0000] {standard_task_runner.py:63} INFO - Started process 393 to run task
[2024-07-15T04:49:26.469+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_pipeline.merge_data manual__2024-07-15T04:42:10.842954+00:00 [running]> on host 37d6808b0cee
[2024-07-15T04:49:26.553+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your_email@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='merge_data' AIRFLOW_CTX_EXECUTION_DATE='2024-07-15T04:42:10.842954+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-15T04:42:10.842954+00:00'
[2024-07-15T04:49:26.554+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-15T04:49:27.853+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-07-15T04:49:27.854+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-15T04:49:27.861+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/demo.py", line 58, in merge_data
    df_merged = pd.merge(df_csv, df_xlsx, left_on='matched_company_name', right_on='owner', how='left')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/reshape/merge.py", line 183, in merge
    return op.get_result(copy=copy)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/reshape/merge.py", line 885, in get_result
    result = self._reindex_and_concat(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/reshape/merge.py", line 876, in _reindex_and_concat
    result = concat([left, right], axis=1, copy=copy)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/reshape/concat.py", line 393, in concat
    return op.get_result()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/reshape/concat.py", line 680, in get_result
    new_data = concatenate_managers(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/internals/concat.py", line 131, in concatenate_managers
    mgrs = _maybe_reindex_columns_na_proxy(axes, mgrs_indexers, needs_copy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/internals/concat.py", line 230, in _maybe_reindex_columns_na_proxy
    mgr = mgr.copy()
          ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/internals/managers.py", line 587, in copy
    res._consolidate_inplace()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/internals/managers.py", line 1750, in _consolidate_inplace
    self.blocks = _consolidate(self.blocks)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/internals/managers.py", line 2217, in _consolidate
    merged_blocks, _ = _merge_blocks(
                       ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/internals/managers.py", line 2252, in _merge_blocks
    bp = BlockPlacement(new_mgr_locs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-07-15T04:49:27.896+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_pipeline, task_id=merge_data, run_id=manual__2024-07-15T04:42:10.842954+00:00, execution_date=20240715T044210, start_date=20240715T044926, end_date=20240715T044927
[2024-07-15T04:49:27.982+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 2
[2024-07-15T04:49:27.991+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
